# Generated by Django 4.1.2 on 2022-10-04 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=17, null=True)),
                ('last_name', models.CharField(max_length=20, null=True)),
                ('location', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=10, null=True)),
                ('blood_type', models.CharField(max_length=5, null=True)),
                ('age', models.CharField(max_length=20, null=True)),
                ('last_time_donated', models.DateTimeField(default='', max_length=10, null=True)),
            ],
        ),
    ]
