# Generated by Django 4.1.2 on 2022-10-04 19:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redwingsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donors',
            name='last_time_donated',
            field=models.DateTimeField(default=datetime.datetime.now, max_length=10, null=True),
        ),
    ]
